test: Attempt at fixing incidental test failure on py3 in Travis.
We got these errors from Travis.

The first one after force-pushing. Possibly the error was caused by a
container termination because of the build reset?

    ======================================================================
    ERROR: test_post_actual_data (exactonline.http_test.HttpTestCase)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "exactonline/http_test.py", line 134, in test_post_actual_data
        'http://127.0.0.1:%d/path' % (server.port,), data=indata)
      File "exactonline/http.py", line 254, in http_post
        return _http_request(url, method='POST', data=_marshalled(data), opt=opt)
      File "exactonline/http.py", line 321, in _http_request
        exc_info[1].url,
    AttributeError: 'ConnectionResetError' object has no attribute 'url'

This error was thrown on the new commit. This should not happen without
the shutdown(RDWR) either, but adding it can't hurt.

    ======================================================================
    ERROR: test_exception_str (exactonline.http_test.HttpTestCase)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "exactonline/http_test.py", line 163, in test_exception_str
        http_post(url, data='{"action":1}')
      File "exactonline/http.py", line 254, in http_post
        return _http_request(url, method='POST', data=_marshalled(data), opt=opt)
      File "exactonline/http.py", line 315, in _http_request
        response = fp.read()
      File "/opt/python/3.6-dev/lib/python3.6/http/client.py", line 459, in read
        s = self.fp.read()
      File "/opt/python/3.6-dev/lib/python3.6/socket.py", line 586, in readinto
        return self._sock.recv_into(b)
    ConnectionResetError: [Errno 104] Connection reset by peer