compatibility: Fix Python23 issues with non-native-strings in URIs.
Some overzealous encoding was going on. Everyone expects native-strings
now. And if you use a storage backend that does not, the
ExactOnlineConfig will convert the data to native-strings anyway.

This fixes this error, and future-proofs things a bit:

      File "example.py" line 10, in
        invoice = api.invoices.get(invoice_number='16700002')
    ...
      File "exactonline/api/manager.py", line 81, in filter
        ret = self._api.restv1('GET', self.resource + args)
      File "exactonline/api/v1division.py", line 29, in restv1
        return self.rest(method, resource, data=data)
    ...
     File "exactonline/rawapi.py", line 83, in refresh_token
        response = http_post(url, refresh_data, opt=opt_secure)
      File "exactonline/http.py", line 254, in _http_request
        proto = url.split(':', 1)[0]
    TypeError: 'str' does not support the buffer interface

or:

    TypeError: a bytes-like object is required, not 'str'

(closes #5)